server:
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /api/v1/

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  application:
    name: wavesend
  cloud:
    vault:
      uri: http://localhost:8200
      authentication: TOKEN
      token: root
      kv:
        enabled: true
        backend: secret
        default-context: application
        version: 2
  config:
    import:  vault://

  datasource:
    url: jdbc:postgresql://localhost:5432/money_transfer
    username: shizzy
    password: password

  flyway:
    baseline-on-migrate: true
    enabled: true

  devtools:
    restart:
      exclude: /db/migration/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/wavesend"

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: transactionNotification:com.shizzy.moneytransfer.dto.TransactionNotification

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: transactionNotification:com.shizzy.moneytransfer.dto.TransactionNotification


  jackson:
    serialization:
      write-dates-as-timestamps: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: wavesendcc@gmail.com
    password: rqzo mgfd boib nave
    properties:
      mail:
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
        smtp:
          starttls:
            enable: true
          trust: "*"
          socketFactory:
            port: 587
            class: javax.net.ssl.SSLSocketFactory
      auth: true
    protocol: smtp

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: true
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 6000

  data:
    redis:
      host: redis
      port: 6379

cache:
  config:
    entryTtl: 60
    transactions:
      entryTtl: 60

application:
  mailing:
    frontend:
        activation-url: http://localhost:4200/activate-account
        password-reset-url: http://localhost:4200/reset-password

stripe:
  api-key: sk_test_51OaEANBL7OKV3Jro3LpUN1E96A4oCmptMcHzjKDTAgp2cXmyzV1Mum5AfxlztB0K44nL6v0dMI5T1vlxENeTvLM700WXYXraag
  webhook:
    secret: whsec_SkA8jLMDeQ930AJQ37OHEnDuv2xPh3ar

springdoc:
  default-produces-media-type: application/json

logging:
  level:
    com.shizzy.moneytransfer.service: INFO
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG

flutterwave:
  api:
    key: FLWSECK_TEST-8a276dc1f16a69a2bf4c0d22746f3e08-X
    live-key: FLWSECK-04e051efccd6322a1e7bfe1ce3a9023f-18fcd566b14vt-X
    base-url: https://api.flutterwave.com/v3
    secret-hash: c9ef5f60f6c3ec12971c064091f8fa2a4a7249f2

paystack:
  api:
    key: sk_test_901cb2419db29d3ff23df3ae3a5345acdaaadc0a
    base-url: https://api.paystack.co

twilio:
  account:
    sid: AC4705794cf720ce167f2a32be39286eef
  auth:
    token: d07723d45d3b7f6a99789427f2dc0e0e
  phone: +234 912 231 4170

termii:
  api:
    base-url: https://v3.api.termii.com
    api-key: TLnYaBfGaOIuyyYJRQcmrufmSsJLQQMjDRODcXTzdNnQQUyxsRpiiRwwApQoxo


keycloak:
  event-listener:
    endpoint-secret: 4AA7716BCB9BCEE78311A6D2DABB5D3A
    endpoint-url:  https://ca48-2c0f-2a80-73-f910-d525-40e6-4b87-dfd7.ngrok-free.app


mailer-send:
  api-token: mlsn.44014087836e630dd1c371ffabdeb4b8b04f96a41f9bb42de6de0a336e42f3b4

aws:
  region: eu-west-1
  s3:
    buckets:
      wavesend: wavesend